# Override file for local development
# This file is automatically loaded by docker-compose
version: '3.8'

services:
  app-dev:
    environment:
      # Override with local environment variables if they exist
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      SESSION_SECRET: ${SESSION_SECRET:-docker-dev-secret}
    volumes:
      # Additional volume mounts for development
      - ./.env.docker:/app/.env:ro
    command: ["npm", "run", "dev"]

  postgres:
    # Expose postgres port for direct access during development
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@ambient.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}